export type brandListType = {
  srNo?: number;
  id: number;
  brandName: string;
  subCategory: string;
  investmentRange: string;
  numberOfLocations: string;
  franchiseFee: string;
  areaaRequired: string;
  active: boolean;
  approved: boolean;
};

export type BrandEditDataType = {
  id: number;
  fullName: string;
  email: string;
  countryCode: string;
  phoneNumber: string;
  pincode: string | null;
  userCity: number;
  userState: number;
  kylasLeadId: string | null;
  companyName: string;
  websiteURL: string;
  brandName: string;
  industry: number;
  subCategory: number;
  headquartersLocation: number;
  service: number;
  businessCommencedYear: string;
  franchiseCommencedYear: string;
  numberOfLocations: number;
  brandDescription: string;
  usp: string;
  country: number;
  state: number[];
  city: number[];
  areaRequired: number;
  investmentRange: number;
  franchiseFee: string;
  salesRevenueModel: number[];
  roi: number;
  paybackPeriod: number;
  tenurePeriod: number | null;
  supportProvided: number[];
  otherApplicable: string | null;
  isOperatingManuals: boolean;
  isAssistanceAvailable: boolean;
  isExpertGuidance: boolean;
  isITSystemIncluded: boolean;
  trainingLocation: boolean;
  brochure: string;
  logo: string;
  brandImages: string[];
  video: string;
  franchiseAggrementFile: string | null;
  franchiseAgreement: boolean;
  franchiseDuration: number;
  isRenewable: boolean;
  active: boolean;
  approved: boolean;
  deletedAt: string | null;
  createdAt: string;
  updatedAt: string;
};
